//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockQuantity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsShelfLife
    {
        public long ItemCode { get; set; }
        public string DesignCode { get; set; }
        public string CategoryName { get; set; }
        public string ClassName { get; set; }
        public string SubClassName { get; set; }
        public string ItemName { get; set; }
        public string UnitName { get; set; }
        public string SizeName { get; set; }
        public string ColorName { get; set; }
        public string SourceName { get; set; }
        public string VendorName { get; set; }
        public string GroupName { get; set; }
        public string TypeName { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<double> ShelfLife { get; set; }
    }
}
