//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockQuantity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AliFashionEntities1 : DbContext
    {
        public AliFashionEntities1()
            : base("name=AliFashionEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ShelfLife> ShelfLives { get; set; }
        public virtual DbSet<shelfLifeBak> shelfLifeBaks { get; set; }
        public virtual DbSet<newItemStockTrack> newItemStockTracks { get; set; }
        public virtual DbSet<AvgIntervalShelf> AvgIntervalShelves { get; set; }
        public virtual DbSet<ItemsShelfLife> ItemsShelfLives { get; set; }
    }
}
