//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockQuantity
{
    using System;
    using System.Collections.Generic;
    
    public partial class shelfLifeBak
    {
        public string itemCode { get; set; }
        public Nullable<int> interval { get; set; }
        public Nullable<int> shopCode { get; set; }
        public Nullable<double> shlefLife { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
